python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R01/RaftRun10861.p R01 ITL $OBS_LSST_DIR/policy/lsstCam/R01.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R02/RaftRun10982.p R02 ITL $OBS_LSST_DIR/policy/lsstCam/R02.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R03/RaftRun11166.p R03 ITL $OBS_LSST_DIR/policy/lsstCam/R03.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R10/RaftRun10517.p R10 ITL $OBS_LSST_DIR/policy/lsstCam/R10.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R11/RaftRun10669.p R11 E2V $OBS_LSST_DIR/policy/lsstCam/R11.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R12/RaftRun11415.p R12 E2V $OBS_LSST_DIR/policy/lsstCam/R12.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R13/RaftRun11808.p R13 E2V $OBS_LSST_DIR/policy/lsstCam/R13.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R14/RaftRun11746.p R14 E2V $OBS_LSST_DIR/policy/lsstCam/R14.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R20/RaftRun10928.p R20 ITL $OBS_LSST_DIR/policy/lsstCam/R20.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R21/RaftRun10722.p R21 E2V $OBS_LSST_DIR/policy/lsstCam/R21.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R22/RaftRun11351.p R22 E2V $OBS_LSST_DIR/policy/lsstCam/R22.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R23/RaftRun11852.p R23 E2V $OBS_LSST_DIR/policy/lsstCam/R23.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R24/RaftRun11952.p R24 E2V $OBS_LSST_DIR/policy/lsstCam/R24.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R30/RaftRun11063.p R30 E2V $OBS_LSST_DIR/policy/lsstCam/R30.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R31/RaftRun11903.p R31 E2V $OBS_LSST_DIR/policy/lsstCam/R31.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R32/RaftRun12002.p R32 E2V $OBS_LSST_DIR/policy/lsstCam/R32.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R33/RaftRun12139.p R33 E2V $OBS_LSST_DIR/policy/lsstCam/R33.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R34/RaftRun12027.p R34 E2V $OBS_LSST_DIR/policy/lsstCam/R34.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R41/RaftRun12086.p R41 ITL $OBS_LSST_DIR/policy/lsstCam/R41.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R42/RaftRun12120.p R42 ITL $OBS_LSST_DIR/policy/lsstCam/R42.yaml
python $OBS_LSST_DIR/bin.src/update_raft.py /project/shared/bxin/cam_as_built/R43/RaftRun11671.p R43 ITL $OBS_LSST_DIR/policy/lsstCam/R43.yaml
